### PR TITLE
Main page- Newsweek-clone

### PR DESCRIPTION
**Pull request by george-shammar**
This pull request seeks to merge the following features to the main branch.

1. Main page has been made responsive to different device displays: Small devices, Medium devices and large devices.

2. 768px and 992px breakpoints were adopted for medium and large screens respectively.

3. Navigation bar- Made to transition according to the different break points.

4. Page content including media files have been organized as it is on the original web page of the Newsweek using flex and grid.

5. Different sections of the page include: Top Stories, Feature Stories, U.S, Sports, Tech, My Turn, Culture, Business, The Debate, Opinion, The Magazine, Editor's pick.

6. The footer which includes logo, social media icons and several other links.

### CODE REVIEW

**Review by abredi — CHANGES_REQUESTED** [review]
## Status: Require changes 🌳 ♲ ##
Hi @gscarv13  and @george-shammar , 👏 You did very well on this project. ✨ I applaud you for successfully replicating the Newsweek home page. Most requirements are have done 👌, Kindly fix the following issues.

[REQUIRED]
- [ ] Fix web hint and stylelint linting errors 

- [ ] Fix horizontal scrolling issue on medium-sized screens. The articles in the 'In the Magazine' section are causing this issue.
inthe_magazine


- [ ] Adjust the bottom section of the page ('Subscribe' and 'Newsletter') to look similar to the original web page in all screen sizes.

| Your Copy | Source |
| :---: | :---: |
|||

Copy on Large Screen
large_copy

Original on Large Screen large_original

- [ ] Fix the footer, change the color of the Newsweek logo, and adjust the placement of the elements to make it similar to the original page.

Your Copy  footer_copy 
 Original footer_original


- [x] Fix the 'Readme' file, make it easier to read and add a live link.

Once you fix the issues, kindly submit another code review. ♲
 Happy coding 👨‍💻
 Abdulaziz Redi Ali

**Review by abredi — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating newsweek.com. Kindly fix the issues stated in the previous review. 

- [ ] Avoid/Decrease `!important` rules from the CSS
- [x] Fix the linting errors
- [ ] Reorder the sections on mobile views the Top News should be on the top.
- [x] Give blank space on the right and left of the page


| Your Copy | Source | 
| :---:         |     :---:      |
| Screen Shot 2020-12-10 at 9 50 37 PM|Screen Shot 2020-12-10 at 9 50 15 PM|



Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello there @george-shammar and @gscarv13  👋 👋 

✔️ Good job on working on the feedback given by the previous TSE
✔️  Your project looks really great, it almost looks like the original page
✔️ I like the project description and technologies used on the README file

However, before we mark the project as complete, check out the comments below ⬇️ 

- [ ]  As the previous TSE mentioned, avoid using !important in a CSS file. It is bad practice and should be avoided because it makes debugging more difficult by breaking the natural cascading in your stylesheets. Kindly work on removing it.

- [ ] On the tablet view, the user icon should actually be a text named `Login`. 

Original | Clone
------------ | -------------
image | image

-  Let's make the README file even better by making the following changes. Refer to this [template](https://github.com/microverseinc/readme-template) . You can choose to download the template, edit it then push it on your repo.

- [ ]  Add a sample screenshot of the project to the file.

- [ ]  Add a live version link of your project. You can use [gh-pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site) to host your website. It is pretty easy.

- [ ]  Add the getting started section. In this section, explain to a user who has never used GitHub before how to use your project. 😄 

- [ ] Style the author's section in an orderly manner. Refer to the above template on how to do this.

- [ ] Contributions and feature requests are welcome!  -> this should be a paragraph under contributions, not a heading as it is currently.

- [ ] Issue request are welcome! -> this should be a paragraph under issues, not  a heading as it is currently

- [ ] Feel free to check the link: The original page: https://www.newsweek.com/  -> make this a paragraph under contributions or acknowledgments

- [ ] Show your support -> This should be a heading and  Give a star if you like this project! -> should be a paragraph under it.


 That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team,
You have done an amazingly great job on this project. It is good to go but before it can be approved you have to remove all use of `!important ` in your CSS. As explained by the previous reviewer, it is bad practice and should be avoided.
Please make the change and request another review.
slack(@ebeagusamuel)

**Comment by gscarv13** [comment]
> # Changes Required ♻️
> Hello team,
> You have done an amazingly great job on this project. It is good to go but before it can be approved you have to remove all use of `!important ` in your CSS. As explained by the previous reviewer, it is bad practice and should be avoided.
> Please make the change and request another review.
> slack(@ebeagusamuel)

Hello Ebeagu, 

I removed all !important statements but one. This last one is necessary to make the layout of the navbar work on mobile devices. 
For some reason, the breakpoint of bootstrap is not working correctly for small screens such as iPhone 5/SE

Please, have a look at this screenshot:
This is how the page looks like using the d-sm-none class:

Capturar6

**Comment by arslanbisharat** [comment]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:



_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
